In [1]:
import hazm
wordEmbedding = hazm.WordEmbedding(model_type='fasttext')
wordEmbedding.load_model('fasttext_skipgram_300.bin')

NameError: name 'hazm' is not defined

In [2]:
import hazm
import pandas as pd
import json
import nlp

In [3]:
print("pls wait until training completed...")
json_file = open(f"../json_file/intents.json", 'r',
                     encoding="utf8")

intents = json.load(json_file)
json_file.close()

words = []
classes = []
documents = []

for intent in intents['intents']:
    for pattern in intent["patterns"]:
        word_list = nlp.clean_up_sentence(pattern)
        words.extend(word_list)
        documents.append((word_list, intent["tag"]))
        if intent["tag"] not in classes:
            classes.append(intent['tag'])

words = sorted(set(words))
classes = sorted(set(classes))
   

pls wait until training completed...
normalize:  ['سلام']
normalize:  ['سلام', 'مشکل', 'پیش', 'آمد#آ', 'برایم']
normalize:  ['سلام', 'وقت', 'شما', 'بخیر']
normalize:  ['خیر', 'امروز', 'جهت', 'ارسال', 'باید', 'به', 'پست', 'تحویل', 'داد#ده', 'که', 'مشکل', 'داشت', 'توانست#توان', 'تحویل', 'بد']
normalize:  ['ممنون', 'خدانگهدار']
normalize:  ['خدانگهدار']
normalize:  ['تشکر', 'خداحافظ']
normalize:  ['شما', 'آقا']
normalize:  ['شما', 'کدام', 'پشتیبان', '#هست']
normalize:  ['شما', 'کی', '#هست']
normalize:  ['ساعت', 'پشتیبان', 'به', 'چه', 'صورته است']
normalize:  ['چه', 'ساعت', 'هایی', 'پاسخگو', '#هست']
normalize:  ['چه', 'زمان', 'هایی', 'توانست#توان', 'از', 'شما', 'سوال', 'پرسید#پرس']


In [4]:
words

['#هست',
 'آقا',
 'آمد#آ',
 'ارسال',
 'از',
 'امروز',
 'باید',
 'بخیر',
 'بد',
 'برایم',
 'به',
 'تحویل',
 'تشکر',
 'توانست#توان',
 'جهت',
 'خداحافظ',
 'خدانگهدار',
 'خیر',
 'داد#ده',
 'داشت',
 'زمان',
 'ساعت',
 'سلام',
 'سوال',
 'شما',
 'صورته است',
 'مشکل',
 'ممنون',
 'هایی',
 'وقت',
 'پاسخگو',
 'پرسید#پرس',
 'پست',
 'پشتیبان',
 'پیش',
 'چه',
 'کدام',
 'که',
 'کی']

df

In [5]:
classes

['اسم و فامیل', 'خداحافظی', 'خوش آمدگویی', 'ساعت کاری']

In [6]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [7]:
from tensorflow.keras.preprocessing.text import Tokenizer
max_words = len(words)
tkn = Tokenizer(num_words=max_words)
tkn.fit_on_texts(intent[0] for intent in documents)
seq = tkn.texts_to_sequences(intent[0] for intent in documents)
seq

[[2],
 [2, 5, 13, 14, 15],
 [2, 16, 1, 17],
 [18, 19, 20, 21, 22, 6, 23, 7, 24, 25, 5, 26, 8, 7, 27],
 [28, 9],
 [9],
 [29, 30],
 [1, 31],
 [1, 32, 10, 3],
 [1, 33, 3],
 [11, 10, 6, 4, 34],
 [4, 11, 12, 35, 3],
 [4, 36, 12, 8, 37, 1, 38]]

In [8]:
import numpy as np
train_y = [intent[1] for intent in documents]
print(train_y)


d = dict(zip(classes, range(0, len(classes))))
train_y = [[d[word]] for word in train_y]
train_y = list(train_y)
print(train_y)
train_y = np.array(train_y)
print(train_y)

['خوش آمدگویی', 'خوش آمدگویی', 'خوش آمدگویی', 'خوش آمدگویی', 'خداحافظی', 'خداحافظی', 'خداحافظی', 'اسم و فامیل', 'اسم و فامیل', 'اسم و فامیل', 'ساعت کاری', 'ساعت کاری', 'ساعت کاری']
[[2], [2], [2], [2], [1], [1], [1], [0], [0], [0], [3], [3], [3]]
[[2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [3]
 [3]
 [3]]


In [9]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [10]:
max_len = 20
paded_docs = pad_sequences(seq,maxlen=max_len,padding="pre")
# paded_docs = list(paded_docs) #x_train


# print(train_x)
# paded_docs = np.array(paded_docs)
print(paded_docs)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  5 13 14 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2 16  1 17]
 [ 0  0  0  0  0 18 19 20 21 22  6 23  7 24 25  5 26  8  7 27]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 28  9]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  9]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 29 30]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1 31]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1 32 10  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1 33  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 11 10  6  4 34]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  4 11 12 35  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  4 36 12  8 37  1 38]]


In [11]:
from tensorflow.keras.models import Sequential
from tensorflow import keras
from keras.layers import Dense
from keras.models import Sequential, load_model
from tensorflow.keras.layers import LSTM,Activation,Dense, Dropout ,Input, Embedding

In [12]:
embedding_vector_features = 30
model = Sequential()
model.add(Embedding(max_words,embedding_vector_features,input_length=max_len))
model.add(LSTM(256))
model.add(Dense(len(classes), activation='softmax'))
model.compile(optimizer='adam',loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 30)            1170      
                                                                 
 lstm (LSTM)                 (None, 256)               293888    
                                                                 
 dense (Dense)               (None, 4)                 1028      
                                                                 
Total params: 296,086
Trainable params: 296,086
Non-trainable params: 0
_________________________________________________________________


In [16]:
print(train_y)
print(paded_docs)
model.fit(paded_docs,train_y,batch_size=128,epochs=10)

[[2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [3]
 [3]
 [3]]
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  5 13 14 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2 16  1 17]
 [ 0  0  0  0  0 18 19 20 21 22  6 23  7 24 25  5 26  8  7 27]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 28  9]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  9]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 29 30]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1 31]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1 32 10  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1 33  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 11 10  6  4 34]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  4 11 12 35  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  4 36 12  8 37  1 38]]
Epoch 1/10


ValueError: in user code:

    File "c:\Users\sedwna\.conda\envs\conversation_AI\lib\site-packages\keras\engine\training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\sedwna\.conda\envs\conversation_AI\lib\site-packages\keras\engine\training.py", line 1146, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\sedwna\.conda\envs\conversation_AI\lib\site-packages\keras\engine\training.py", line 1135, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\sedwna\.conda\envs\conversation_AI\lib\site-packages\keras\engine\training.py", line 994, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "c:\Users\sedwna\.conda\envs\conversation_AI\lib\site-packages\keras\engine\training.py", line 1052, in compute_loss
        return self.compiled_loss(
    File "c:\Users\sedwna\.conda\envs\conversation_AI\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "c:\Users\sedwna\.conda\envs\conversation_AI\lib\site-packages\keras\losses.py", line 152, in __call__
        losses = call_fn(y_true, y_pred)
    File "c:\Users\sedwna\.conda\envs\conversation_AI\lib\site-packages\keras\losses.py", line 272, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "c:\Users\sedwna\.conda\envs\conversation_AI\lib\site-packages\keras\losses.py", line 1990, in categorical_crossentropy
        return backend.categorical_crossentropy(
    File "c:\Users\sedwna\.conda\envs\conversation_AI\lib\site-packages\keras\backend.py", line 5529, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes (None, 1) and (None, 4) are incompatible
